name: Readme sync action

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install rdme CLI globally
        run: npm install -g rdme

      - name: Download OpenAPI JSON
        run: curl -o swagger.json https://external-api.prod.baseerp.com.br/v3/api-docs

      - name: Upload to ReadMe
        run: echo "y" | rdme openapi upload swagger.json --key=${{ secrets.README_API_KEY }} --branch=1.0 --slug=external-apiprodbaseerpcombr-v3api-docs.json
