name: Readme sync action

on:
  schedule:
    # - cron: "0 20 * * 1-5"
    # - cron: "0 13 * * 1-5" # 09:25 BRT (UTC-3)
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rdme
        run: npm install -g rdme@10

      - name: Download external OpenAPI JSON
        run: curl -o swagger.json https://external-api.prod.baseerp.com.br/v3/api-docs

      - name: Upload to ReadMe
        run: rdme openapi upload swagger.json --key=${{ secrets.README_API_KEY }} --branch=1.0 --slug=external-apiprodbaseerpcombr-v3api-docs.json
# TODO change slug to correct one