name: Readme sync action

on:
  workflow_dispatch:

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Install rdme
        run: npm install -g rdme@10

      - name: Download external OpenAPI JSON
        run: curl -fSL -o swagger.json https://external-api.prod.baseerp.com.br/v3/api-docs

      - name: Upload to ReadMe
        run: echo "yes" | rdme openapi upload swagger.json --key=${{ secrets.README_API_KEY }} --branch=1.0 --slug=api-base-by-asaas.json